source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'awesome_print'
  gem 'quiet_assets'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Deployment
  gem 'uniofbath_deploy', git: 'https://fb5836d863323df955aeb5050255cfa9e76b3fcd:x-oauth-basic@github.bath.ac.uk/digital/uniofbath-deploy.git', require: false

  # For use with bamboo:
  # Test reports
  gem 'minitest-reporters'
  # Code linting
  gem 'rubocop'
  # Coverage check
  gem 'simplecov', require: false
  # Security auditing
  gem 'brakeman'

  # For feature testing with Capybara
  gem 'minitest-rails-capybara'
  gem 'selenium-webdriver'
  gem 'capybara-webkit'
end

group :test do
  # Session config during capybara tests
  gem 'rack_session_access'
  gem 'test_after_commit'
end

# CAS client for Single sign-on
gem 'rubycas-client', git: 'https://github.com/rubycas/rubycas-client.git'

# LDAP client for accessing group manager groups
gem 'net-ldap'

# Configuration
gem 'rails_config'
# Server
gem 'unicorn'
# Redis integration
gem 'redis'
# Add secure headers
gem 'secure_headers'
# Logging
gem 'lograge'

# Profiling
gem 'rack-mini-profiler', require: false
gem 'flamegraph'

# Validate dates
gem 'date_validator'
# Version the content items
gem 'paper_trail', '~> 4.2'

# Oracle libs
gem 'ruby-oci8'
gem 'activerecord-oracle_enhanced-adapter', git: 'https://github.com/rsim/oracle-enhanced.git', branch: 'rails42'

# For attachment handling
gem 'carrierwave'

# Pagination
gem 'kaminari'
